_BASE_: "RT-K-Net-Cityscapes.yaml"
MODEL:
  SEM_SEG_HEAD:
    IGNORE_VALUE: 65
    NUM_CLASSES: 65
  TEST:
    INSTANCE_SCORE_THRESHOLD: 0.0
DATASETS:
  TRAIN: ("mapillary_vistas_panoptic_train",)
  TEST: ("mapillary_vistas_panoptic_val",)
SOLVER:
  BASE_LR: 0.0001
  WARMUP_ITERS: 0
  MAX_ITER: 300000
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 2048) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 8192
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TEST: 2048
  CROP:
    SIZE: (1024, 1024)
  SIZE_DIVISIBILITY: 1024  # used in dataset mapper
TEST:
  EVAL_PERIOD: 10000